version: '3'
services: 
  api:
    build: 
      context: "../api"
      dockerfile: "Dockerfile.dev"
    ports:
      - "3001:3000"
    volumes:
      - /usr/app/node_modules
      - ../api:/usr/app  